#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pydot
Version  : 1.3.0
Release  : 18
URL      : https://files.pythonhosted.org/packages/62/a6/721ef123997c81422b725bf1563a3bcb318768e44c5926c847b52791d5f9/pydot-1.3.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/62/a6/721ef123997c81422b725bf1563a3bcb318768e44c5926c847b52791d5f9/pydot-1.3.0.tar.gz
Summary  : Python interface to Graphviz's Dot
Group    : Development/Tools
License  : MIT
Requires: pydot-license = %{version}-%{release}
Requires: pydot-python = %{version}-%{release}
Requires: pydot-python3 = %{version}-%{release}
Requires: chardet
Requires: graphviz
Requires: nose
Requires: pyparsing
BuildRequires : buildreq-distutils3
BuildRequires : pyparsing

%description
A Python interface to GraphViz and the DOT language.
        
        This package includes an interface to GraphViz [1], with classes to represent
        graphs and dump them in the DOT language [2], and a parser from DOT.

%package license
Summary: license components for the pydot package.
Group: Default

%description license
license components for the pydot package.


%package python
Summary: python components for the pydot package.
Group: Default
Requires: pydot-python3 = %{version}-%{release}

%description python
python components for the pydot package.


%package python3
Summary: python3 components for the pydot package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pydot package.


%prep
%setup -q -n pydot-1.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1542617335
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pydot
cp LICENSE %{buildroot}/usr/share/package-licenses/pydot/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pydot/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
